# Generated by Django 5.0.3 on 2024-05-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banzuke", "0004_alter_basho_end_date_alter_basho_start_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="torikumi",
            name="id",
        ),
        migrations.AddField(
            model_name="torikumi",
            name="bout_number",
            field=models.PositiveSmallIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="torikumi",
            name="slug",
            field=models.CharField(
                default="undefined",
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
            preserve_default=False,
        ),
    ]
