# Generated by Django 5.0.3 on 2024-11-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banzuke", "0006_remove_torikumi_bout_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basho",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="basho",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
