# Generated by Django 5.0.3 on 2024-11-12 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banzuke", "0007_alter_basho_end_date_alter_basho_start_date"),
        ("rikishi", "0003_alter_rikishi_api_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="torikumi",
            name="east_rank",
            field=models.ForeignKey(
                default="bg",
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="east_rank",
                to="rikishi.rank",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="torikumi",
            name="west_rank",
            field=models.ForeignKey(
                default="bg",
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="west_rank",
                to="rikishi.rank",
            ),
            preserve_default=False,
        ),
    ]
