# Generated by Django 5.0.3 on 2024-11-12 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banzuke", "0008_torikumi_east_rank_torikumi_west_rank"),
        ("rikishi", "0003_alter_rikishi_api_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="torikumi",
            name="east_rank",
            field=models.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="east_rank",
                to="rikishi.rank",
            ),
        ),
        migrations.AlterField(
            model_name="torikumi",
            name="west_rank",
            field=models.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="west_rank",
                to="rikishi.rank",
            ),
        ),
    ]
