# Generated by Django 5.0.3 on 2024-11-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("glicko", "0003_alter_glicko_vol_alter_glickohistory_vol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glicko",
            name="vol",
            field=models.FloatField(default=0.11, editable=False),
        ),
        migrations.AlterField(
            model_name="glickohistory",
            name="vol",
            field=models.FloatField(default=0.11, editable=False),
        ),
    ]
