# Generated by Django 5.0.3 on 2024-04-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rikishi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rank',
            options={'ordering': ['division', 'order', 'direction']},
        ),
        migrations.AlterModelOptions(
            name='rikishi',
            options={'ordering': ['name'], 'verbose_name_plural': 'Rikishi'},
        ),
        migrations.AddField(
            model_name='rank',
            name='level',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
