# Generated by Django 5.0.3 on 2024-05-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rikishi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="division",
            name="name",
            field=models.CharField(
                choices=[
                    ("Makuuchi", "Makuuchi"),
                    ("Juryo", "Juryo"),
                    ("Makushita", "Makushita"),
                    ("Sandanme", "Sandanme"),
                    ("Jonidan", "Jonidan"),
                    ("Jonokuchi", "Jonokuchi"),
                    ("Mae-zumo", "Mae-zumo"),
                    ("Banzuke-gai", "Banzuke-gai"),
                ],
                editable=False,
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="rank",
            name="title",
            field=models.CharField(
                choices=[
                    ("Yokozuna", "Yokozuna"),
                    ("Ozeki", "Ozeki"),
                    ("Sekiwake", "Sekiwake"),
                    ("Komusubi", "Komusubi"),
                    ("Maegashira", "Maegashira"),
                    ("Juryo", "Juryo"),
                    ("Makushita", "Makushita"),
                    ("Sandanme", "Sandanme"),
                    ("Jonidan", "Jonidan"),
                    ("Jonokuchi", "Jonokuchi"),
                    ("Mae-zumo", "Mae-zumo"),
                    ("Banzuke-gai", "Banzuke-gai"),
                ],
                editable=False,
                max_length=12,
            ),
        ),
    ]
